import { createClient } from '@/lib/supabase/server'
import { NextRequest, NextResponse } from 'next/server'

export async function POST(req: NextRequest) {
  try {
    const { exhibitionId } = await req.json()

    console.log('[HTML] Received exhibition ID:', exhibitionId)

    if (!exhibitionId) {
      return NextResponse.json(
        { error: 'Exhibition ID is required' },
        { status: 400 }
      )
    }

    const supabase = await createClient()

    // Fetch exhibition data
    const { data: exhibition, error: exhibitionError } = await supabase
      .from('exhibitions')
      .select('*')
      .eq('id', exhibitionId)
      .single()

    console.log('[HTML] Exhibition:', exhibition?.title)

    if (exhibitionError || !exhibition) {
      return NextResponse.json(
        { error: `Exhibition not found: ${exhibitionError?.message || 'Unknown error'}` },
        { status: 404 }
      )
    }

    // Fetch exhibition content
    const { data: content } = await supabase
      .from('exhibition_content')
      .select('*')
      .eq('exhibition_id', exhibitionId)

    console.log('[HTML] Content items:', content?.length)

    // Content mapping helper
    const getContent = (type: string) => {
      const item = content?.find((c: any) => c.content_type === type)
      return item?.content || ''
    }

    // Create simple HTML
    const htmlContent = `
      <!DOCTYPE html>
      <html lang="ko">
      <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>${exhibition.title || '전시 패키지'}</title>
        <style>
          @import url('https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/static/pretendard.css');

          body {
            font-family: 'Pretendard', -apple-system, BlinkMacSystemFont, sans-serif;
            line-height: 1.8;
            max-width: 800px;
            margin: 0 auto;
            padding: 40px 20px;
            color: #1a1a1a;
          }

          h1 {
            font-size: 2.5em;
            margin-bottom: 0.5em;
            color: #000;
            border-bottom: 3px solid #000;
            padding-bottom: 0.3em;
          }

          h2 {
            font-size: 1.8em;
            margin-top: 2em;
            margin-bottom: 0.8em;
            color: #333;
            border-bottom: 2px solid #ddd;
            padding-bottom: 0.3em;
          }

          .keywords {
            display: flex;
            flex-wrap: wrap;
            gap: 10px;
            margin: 20px 0 40px 0;
          }

          .keyword {
            background: #f0f0f0;
            padding: 8px 16px;
            border-radius: 20px;
            font-size: 0.9em;
            color: #555;
          }

          .section {
            margin-bottom: 50px;
            page-break-inside: avoid;
          }

          .content {
            white-space: pre-wrap;
            line-height: 1.9;
          }

          .footer {
            margin-top: 80px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            text-align: center;
            color: #999;
            font-size: 0.9em;
          }

          @media print {
            body {
              padding: 20px;
            }
            .section {
              page-break-inside: avoid;
            }
          }
        </style>
      </head>
      <body>
        <h1>${exhibition.title || '제목 없음'}</h1>

        ${
          exhibition.keywords && exhibition.keywords.length > 0
            ? `<div class="keywords">
                ${exhibition.keywords.map((k: string) => `<span class="keyword">${k}</span>`).join('')}
              </div>`
            : ''
        }

        ${
          getContent('introduction')
            ? `<div class="section">
                <h2>전시 소개</h2>
                <div class="content">${getContent('introduction')}</div>
              </div>`
            : ''
        }

        ${
          getContent('preface')
            ? `<div class="section">
                <h2>전시 서문</h2>
                <div class="content">${getContent('preface')}</div>
              </div>`
            : ''
        }

        ${
          getContent('artist_bio')
            ? `<div class="section">
                <h2>작가 소개</h2>
                <div class="content">${getContent('artist_bio')}</div>
              </div>`
            : ''
        }

        ${
          getContent('press_release')
            ? `<div class="section">
                <h2>보도자료</h2>
                <div class="content">${getContent('press_release')}</div>
              </div>`
            : ''
        }

        <div class="footer">
          <p>Generated by Art Wizard</p>
          <p>${new Date().toLocaleDateString('ko-KR')}</p>
        </div>
      </body>
      </html>
    `

    console.log('[HTML] HTML generated successfully')

    // Return HTML
    return new NextResponse(htmlContent, {
      headers: {
        'Content-Type': 'text/html; charset=utf-8',
        'Content-Disposition': `attachment; filename="${exhibition.title || 'exhibition'}_package.html"`,
      },
    })
  } catch (error) {
    console.error('[HTML] Generate HTML error:', error)
    return NextResponse.json(
      {
        error: 'Failed to generate HTML',
        details: error instanceof Error ? error.message : 'Unknown error'
      },
      { status: 500 }
    )
  }
}
